# Generated by Django 6.0.1 on 2026-01-18 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entrenadores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("edad", models.IntegerField()),
                ("nivel", models.IntegerField(default=1)),
                ("fecha_de_nacimiento", models.DateField(blank=True, null=True)),
                ("descripciones", models.TextField()),
                ("imagen", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="pokemons/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pokemones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=40)),
                ("peso", models.IntegerField()),
                ("altura", models.IntegerField()),
                ("imagen", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="pokemons/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mispokemones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=40)),
                ("peso", models.IntegerField()),
                ("altura", models.IntegerField()),
                ("imagen", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="pokemons/"),
                ),
                (
                    "entrenador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pokedex1.entrenadores",
                    ),
                ),
            ],
        ),
    ]
