# Generated by Django 6.0.1 on 2026-01-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenadores',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
