# Generated by Django 6.0.1 on 2026-01-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex1', '0002_alter_entrenadores_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mispokemones',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemones',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
